### ISSUE TITLE
Mobs reset when moving on a ship

### ISSUE THREAD

**Issue by UltimateCoffee** [Minecraft-Ships/CoreToBukkit#2]
When a mob that contains unique data (such as a horse or a mooshroom) are moved with a ship, they lose their unique data. This causes horses to change color, become untamed, and lose equipped gear, and causes mooshrooms to turn into cows.

Minecraft version 1.16.3
Running latest spigot, and latest version of ships.

**Comment by mosemister** [comment]
This issue should be fixed. Loved to hear if there is any issues

**Comment by mosemister** [comment]
Closed due to lack of activity
